name: Build

on:
  workflow_run:
    workflows:
      - "Tests"
    types:
      - completed

jobs:

  build:
    name: Build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Build
        run: make build

      - name: Upload App Build
        uses: actions/upload-artifact@v2
        # due to possible limitations of artifact upload size limits, we can allow this failure
        continue-on-error: true
        with:
          name: tclient-${{ matrix.platform }}
          path: bin/tclient