name: Lint, Test & Build

on: [ push ]

jobs:
  test:
    name: Unit Tests

    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: make test

  build:
    name: Build

    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}
    
    needs:
      - test

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Build
        run: make build

      - name: Upload App Build
        uses: actions/upload-artifact@v2
        # due to possible limitations of artifact upload size limits, we can allow this failure
        continue-on-error: true
        with:
          name: app-build
          path: bin/main