name: Lint

on: [ push ]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/checkout@v3

      # https://github.com/golangci/golangci-lint-action
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.0